### ISSUE TITLE
vscode markdown PDF 生成指定样式字体

### ISSUE THREAD

**Issue by mygoare** [mygoare/notes#1]
user setting.json
/Users/yourusername/Library/Application Support/Code/User/settings.json

```css
"markdown-pdf.styles": [
    "./markdown.css"
]
```

Markdown: Styles
A list of URLs or local paths to CSS style sheets to use from the markdown preview. Relative paths are interpreted relative to the folder open in the explorer. If there is no open folder, they are interpreted relative to the location of the markdown file. All '\' need to be written as '\\'.

可以把 markdown.css 样式文件 文件 放在 md 文件的相对目录

markdown.css:
写上自己喜欢的 字体 即可

```css
@media print {
    body {
        font-family: "-apple-system, BlinkMacSystemFont, 'Segoe WPC', 'Segoe UI', 'HelveticaNeue-Light', 'Ubuntu', 'Droid Sans', sans-serif";
    }
}
```
